import Head from "next/head";
import "./globals.css";
import Nav from "@/components/Nav";
import Homee from "@/components/Homee";
import About from "@/components/About";
import Services from "@/components/Services";
import Services2 from "@/components/Services2";
import Partners from "@/components/Partners";
import Contact from "@/components/Contact";
import Footer from "@/components/Footer";
import Services3 from "@/components/Services3";

export default function Home() {
  return (
    <div className="main-container">
      <Head>
        <title>My Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Homee />
      <About />
      <Services />
      <Services2 />
      <Services3 />
      <Services2 />
      <Partners />
      <Contact />
      <Footer />
    </div>
  );
}
